### ISSUE TITLE
请问pinry部署之后无法采集怎么解决呢？

### ISSUE THREAD

**Issue by idwalker** [winkidney/winkidney#1]
使用采集插件采集的时候应该是遇到https无法跨域调用的问题

**Comment by winkidney** [comment]
@idwalker Hi : ), 使用浏览器插件是没有跨域问题的，可以把你具体的问题贴道这里吗？另外你自己的站点，如果想采集HTTPS站点的图片，需要你自己部署的实例也是https站点。

目前还没有关于这一点的改进，如果将插件改为当前页面获取图片然后再上传到Pinry可能可以额解决这个问题。

**Comment by idwalker** [comment]
非常感谢，已经通过部署https的服务解决了
